// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: checkOrder.proto

#include "checkOrder.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace fixbug {
class orderMessageResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<orderMessageResponse> _instance;
} _orderMessageResponse_default_instance_;
class orderMessageRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<orderMessageRequest> _instance;
} _orderMessageRequest_default_instance_;
}  // namespace fixbug
static void InitDefaultsscc_info_orderMessageRequest_checkOrder_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::fixbug::_orderMessageRequest_default_instance_;
    new (ptr) ::fixbug::orderMessageRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::fixbug::orderMessageRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_orderMessageRequest_checkOrder_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_orderMessageRequest_checkOrder_2eproto}, {}};

static void InitDefaultsscc_info_orderMessageResponse_checkOrder_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::fixbug::_orderMessageResponse_default_instance_;
    new (ptr) ::fixbug::orderMessageResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::fixbug::orderMessageResponse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_orderMessageResponse_checkOrder_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_orderMessageResponse_checkOrder_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_checkOrder_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_checkOrder_2eproto = nullptr;
static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* file_level_service_descriptors_checkOrder_2eproto[1];

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_checkOrder_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::fixbug::orderMessageResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::fixbug::orderMessageResponse, createtime_),
  PROTOBUF_FIELD_OFFSET(::fixbug::orderMessageResponse, price_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::fixbug::orderMessageRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::fixbug::orderMessageRequest, ordernumber_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::fixbug::orderMessageResponse)},
  { 7, -1, sizeof(::fixbug::orderMessageRequest)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::fixbug::_orderMessageResponse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::fixbug::_orderMessageRequest_default_instance_),
};

const char descriptor_table_protodef_checkOrder_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020checkOrder.proto\022\006fixbug\"9\n\024orderMessa"
  "geResponse\022\022\n\ncreateTime\030\001 \001(\014\022\r\n\005price\030"
  "\002 \001(\005\"*\n\023orderMessageRequest\022\023\n\013orderNum"
  "ber\030\001 \001(\0142U\n\017OrderServiceRPC\022B\n\005check\022\033."
  "fixbug.orderMessageRequest\032\034.fixbug.orde"
  "rMessageResponseB\003\200\001\001b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_checkOrder_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_checkOrder_2eproto_sccs[2] = {
  &scc_info_orderMessageRequest_checkOrder_2eproto.base,
  &scc_info_orderMessageResponse_checkOrder_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_checkOrder_2eproto_once;
static bool descriptor_table_checkOrder_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_checkOrder_2eproto = {
  &descriptor_table_checkOrder_2eproto_initialized, descriptor_table_protodef_checkOrder_2eproto, "checkOrder.proto", 229,
  &descriptor_table_checkOrder_2eproto_once, descriptor_table_checkOrder_2eproto_sccs, descriptor_table_checkOrder_2eproto_deps, 2, 0,
  schemas, file_default_instances, TableStruct_checkOrder_2eproto::offsets,
  file_level_metadata_checkOrder_2eproto, 2, file_level_enum_descriptors_checkOrder_2eproto, file_level_service_descriptors_checkOrder_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_checkOrder_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_checkOrder_2eproto), true);
namespace fixbug {

// ===================================================================

void orderMessageResponse::InitAsDefaultInstance() {
}
class orderMessageResponse::_Internal {
 public:
};

orderMessageResponse::orderMessageResponse()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:fixbug.orderMessageResponse)
}
orderMessageResponse::orderMessageResponse(const orderMessageResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  createtime_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_createtime().empty()) {
    createtime_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.createtime_);
  }
  price_ = from.price_;
  // @@protoc_insertion_point(copy_constructor:fixbug.orderMessageResponse)
}

void orderMessageResponse::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_orderMessageResponse_checkOrder_2eproto.base);
  createtime_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  price_ = 0;
}

orderMessageResponse::~orderMessageResponse() {
  // @@protoc_insertion_point(destructor:fixbug.orderMessageResponse)
  SharedDtor();
}

void orderMessageResponse::SharedDtor() {
  createtime_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void orderMessageResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const orderMessageResponse& orderMessageResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_orderMessageResponse_checkOrder_2eproto.base);
  return *internal_default_instance();
}


void orderMessageResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:fixbug.orderMessageResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  createtime_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  price_ = 0;
  _internal_metadata_.Clear();
}

const char* orderMessageResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bytes createTime = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_createtime();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 price = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          price_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* orderMessageResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:fixbug.orderMessageResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes createTime = 1;
  if (this->createtime().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_createtime(), target);
  }

  // int32 price = 2;
  if (this->price() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_price(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fixbug.orderMessageResponse)
  return target;
}

size_t orderMessageResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:fixbug.orderMessageResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes createTime = 1;
  if (this->createtime().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_createtime());
  }

  // int32 price = 2;
  if (this->price() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_price());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void orderMessageResponse::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:fixbug.orderMessageResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const orderMessageResponse* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<orderMessageResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:fixbug.orderMessageResponse)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:fixbug.orderMessageResponse)
    MergeFrom(*source);
  }
}

void orderMessageResponse::MergeFrom(const orderMessageResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:fixbug.orderMessageResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.createtime().size() > 0) {

    createtime_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.createtime_);
  }
  if (from.price() != 0) {
    _internal_set_price(from._internal_price());
  }
}

void orderMessageResponse::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:fixbug.orderMessageResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void orderMessageResponse::CopyFrom(const orderMessageResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fixbug.orderMessageResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool orderMessageResponse::IsInitialized() const {
  return true;
}

void orderMessageResponse::InternalSwap(orderMessageResponse* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  createtime_.Swap(&other->createtime_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(price_, other->price_);
}

::PROTOBUF_NAMESPACE_ID::Metadata orderMessageResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void orderMessageRequest::InitAsDefaultInstance() {
}
class orderMessageRequest::_Internal {
 public:
};

orderMessageRequest::orderMessageRequest()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:fixbug.orderMessageRequest)
}
orderMessageRequest::orderMessageRequest(const orderMessageRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ordernumber_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_ordernumber().empty()) {
    ordernumber_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.ordernumber_);
  }
  // @@protoc_insertion_point(copy_constructor:fixbug.orderMessageRequest)
}

void orderMessageRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_orderMessageRequest_checkOrder_2eproto.base);
  ordernumber_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

orderMessageRequest::~orderMessageRequest() {
  // @@protoc_insertion_point(destructor:fixbug.orderMessageRequest)
  SharedDtor();
}

void orderMessageRequest::SharedDtor() {
  ordernumber_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void orderMessageRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const orderMessageRequest& orderMessageRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_orderMessageRequest_checkOrder_2eproto.base);
  return *internal_default_instance();
}


void orderMessageRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:fixbug.orderMessageRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ordernumber_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

const char* orderMessageRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bytes orderNumber = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_ordernumber();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* orderMessageRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:fixbug.orderMessageRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes orderNumber = 1;
  if (this->ordernumber().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_ordernumber(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fixbug.orderMessageRequest)
  return target;
}

size_t orderMessageRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:fixbug.orderMessageRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes orderNumber = 1;
  if (this->ordernumber().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_ordernumber());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void orderMessageRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:fixbug.orderMessageRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const orderMessageRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<orderMessageRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:fixbug.orderMessageRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:fixbug.orderMessageRequest)
    MergeFrom(*source);
  }
}

void orderMessageRequest::MergeFrom(const orderMessageRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:fixbug.orderMessageRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.ordernumber().size() > 0) {

    ordernumber_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.ordernumber_);
  }
}

void orderMessageRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:fixbug.orderMessageRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void orderMessageRequest::CopyFrom(const orderMessageRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fixbug.orderMessageRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool orderMessageRequest::IsInitialized() const {
  return true;
}

void orderMessageRequest::InternalSwap(orderMessageRequest* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  ordernumber_.Swap(&other->ordernumber_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::PROTOBUF_NAMESPACE_ID::Metadata orderMessageRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

OrderServiceRPC::~OrderServiceRPC() {}

const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* OrderServiceRPC::descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_checkOrder_2eproto);
  return file_level_service_descriptors_checkOrder_2eproto[0];
}

const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* OrderServiceRPC::GetDescriptor() {
  return descriptor();
}

void OrderServiceRPC::check(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::fixbug::orderMessageRequest*,
                         ::fixbug::orderMessageResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method check() not implemented.");
  done->Run();
}

void OrderServiceRPC::CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                             ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                             const ::PROTOBUF_NAMESPACE_ID::Message* request,
                             ::PROTOBUF_NAMESPACE_ID::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), file_level_service_descriptors_checkOrder_2eproto[0]);
  switch(method->index()) {
    case 0:
      check(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::fixbug::orderMessageRequest*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::fixbug::orderMessageResponse*>(
                 response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::PROTOBUF_NAMESPACE_ID::Message& OrderServiceRPC::GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::fixbug::orderMessageRequest::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::PROTOBUF_NAMESPACE_ID::MessageFactory::generated_factory()
          ->GetPrototype(method->input_type());
  }
}

const ::PROTOBUF_NAMESPACE_ID::Message& OrderServiceRPC::GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::fixbug::orderMessageResponse::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::PROTOBUF_NAMESPACE_ID::MessageFactory::generated_factory()
          ->GetPrototype(method->output_type());
  }
}

OrderServiceRPC_Stub::OrderServiceRPC_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
OrderServiceRPC_Stub::OrderServiceRPC_Stub(
    ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
    ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::PROTOBUF_NAMESPACE_ID::Service::STUB_OWNS_CHANNEL) {}
OrderServiceRPC_Stub::~OrderServiceRPC_Stub() {
  if (owns_channel_) delete channel_;
}

void OrderServiceRPC_Stub::check(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::fixbug::orderMessageRequest* request,
                              ::fixbug::orderMessageResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace fixbug
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::fixbug::orderMessageResponse* Arena::CreateMaybeMessage< ::fixbug::orderMessageResponse >(Arena* arena) {
  return Arena::CreateInternal< ::fixbug::orderMessageResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::fixbug::orderMessageRequest* Arena::CreateMaybeMessage< ::fixbug::orderMessageRequest >(Arena* arena) {
  return Arena::CreateInternal< ::fixbug::orderMessageRequest >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
