// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: checkOrder.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_checkOrder_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_checkOrder_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_checkOrder_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_checkOrder_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_checkOrder_2eproto;
namespace fixbug {
class orderMessageRequest;
class orderMessageRequestDefaultTypeInternal;
extern orderMessageRequestDefaultTypeInternal _orderMessageRequest_default_instance_;
class orderMessageResponse;
class orderMessageResponseDefaultTypeInternal;
extern orderMessageResponseDefaultTypeInternal _orderMessageResponse_default_instance_;
}  // namespace fixbug
PROTOBUF_NAMESPACE_OPEN
template<> ::fixbug::orderMessageRequest* Arena::CreateMaybeMessage<::fixbug::orderMessageRequest>(Arena*);
template<> ::fixbug::orderMessageResponse* Arena::CreateMaybeMessage<::fixbug::orderMessageResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace fixbug {

// ===================================================================

class orderMessageResponse :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fixbug.orderMessageResponse) */ {
 public:
  orderMessageResponse();
  virtual ~orderMessageResponse();

  orderMessageResponse(const orderMessageResponse& from);
  orderMessageResponse(orderMessageResponse&& from) noexcept
    : orderMessageResponse() {
    *this = ::std::move(from);
  }

  inline orderMessageResponse& operator=(const orderMessageResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline orderMessageResponse& operator=(orderMessageResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const orderMessageResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const orderMessageResponse* internal_default_instance() {
    return reinterpret_cast<const orderMessageResponse*>(
               &_orderMessageResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(orderMessageResponse& a, orderMessageResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(orderMessageResponse* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline orderMessageResponse* New() const final {
    return CreateMaybeMessage<orderMessageResponse>(nullptr);
  }

  orderMessageResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<orderMessageResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const orderMessageResponse& from);
  void MergeFrom(const orderMessageResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(orderMessageResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fixbug.orderMessageResponse";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_checkOrder_2eproto);
    return ::descriptor_table_checkOrder_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCreateTimeFieldNumber = 1,
    kPriceFieldNumber = 2,
  };
  // bytes createTime = 1;
  void clear_createtime();
  const std::string& createtime() const;
  void set_createtime(const std::string& value);
  void set_createtime(std::string&& value);
  void set_createtime(const char* value);
  void set_createtime(const void* value, size_t size);
  std::string* mutable_createtime();
  std::string* release_createtime();
  void set_allocated_createtime(std::string* createtime);
  private:
  const std::string& _internal_createtime() const;
  void _internal_set_createtime(const std::string& value);
  std::string* _internal_mutable_createtime();
  public:

  // int32 price = 2;
  void clear_price();
  ::PROTOBUF_NAMESPACE_ID::int32 price() const;
  void set_price(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_price() const;
  void _internal_set_price(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:fixbug.orderMessageResponse)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr createtime_;
  ::PROTOBUF_NAMESPACE_ID::int32 price_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_checkOrder_2eproto;
};
// -------------------------------------------------------------------

class orderMessageRequest :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fixbug.orderMessageRequest) */ {
 public:
  orderMessageRequest();
  virtual ~orderMessageRequest();

  orderMessageRequest(const orderMessageRequest& from);
  orderMessageRequest(orderMessageRequest&& from) noexcept
    : orderMessageRequest() {
    *this = ::std::move(from);
  }

  inline orderMessageRequest& operator=(const orderMessageRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline orderMessageRequest& operator=(orderMessageRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const orderMessageRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const orderMessageRequest* internal_default_instance() {
    return reinterpret_cast<const orderMessageRequest*>(
               &_orderMessageRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(orderMessageRequest& a, orderMessageRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(orderMessageRequest* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline orderMessageRequest* New() const final {
    return CreateMaybeMessage<orderMessageRequest>(nullptr);
  }

  orderMessageRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<orderMessageRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const orderMessageRequest& from);
  void MergeFrom(const orderMessageRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(orderMessageRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fixbug.orderMessageRequest";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_checkOrder_2eproto);
    return ::descriptor_table_checkOrder_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOrderNumberFieldNumber = 1,
  };
  // bytes orderNumber = 1;
  void clear_ordernumber();
  const std::string& ordernumber() const;
  void set_ordernumber(const std::string& value);
  void set_ordernumber(std::string&& value);
  void set_ordernumber(const char* value);
  void set_ordernumber(const void* value, size_t size);
  std::string* mutable_ordernumber();
  std::string* release_ordernumber();
  void set_allocated_ordernumber(std::string* ordernumber);
  private:
  const std::string& _internal_ordernumber() const;
  void _internal_set_ordernumber(const std::string& value);
  std::string* _internal_mutable_ordernumber();
  public:

  // @@protoc_insertion_point(class_scope:fixbug.orderMessageRequest)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ordernumber_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_checkOrder_2eproto;
};
// ===================================================================

class OrderServiceRPC_Stub;

class OrderServiceRPC : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline OrderServiceRPC() {};
 public:
  virtual ~OrderServiceRPC();

  typedef OrderServiceRPC_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void check(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::fixbug::orderMessageRequest* request,
                       ::fixbug::orderMessageResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(OrderServiceRPC);
};

class OrderServiceRPC_Stub : public OrderServiceRPC {
 public:
  OrderServiceRPC_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  OrderServiceRPC_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~OrderServiceRPC_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements OrderServiceRPC ------------------------------------------

  void check(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::fixbug::orderMessageRequest* request,
                       ::fixbug::orderMessageResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(OrderServiceRPC_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// orderMessageResponse

// bytes createTime = 1;
inline void orderMessageResponse::clear_createtime() {
  createtime_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& orderMessageResponse::createtime() const {
  // @@protoc_insertion_point(field_get:fixbug.orderMessageResponse.createTime)
  return _internal_createtime();
}
inline void orderMessageResponse::set_createtime(const std::string& value) {
  _internal_set_createtime(value);
  // @@protoc_insertion_point(field_set:fixbug.orderMessageResponse.createTime)
}
inline std::string* orderMessageResponse::mutable_createtime() {
  // @@protoc_insertion_point(field_mutable:fixbug.orderMessageResponse.createTime)
  return _internal_mutable_createtime();
}
inline const std::string& orderMessageResponse::_internal_createtime() const {
  return createtime_.GetNoArena();
}
inline void orderMessageResponse::_internal_set_createtime(const std::string& value) {
  
  createtime_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void orderMessageResponse::set_createtime(std::string&& value) {
  
  createtime_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fixbug.orderMessageResponse.createTime)
}
inline void orderMessageResponse::set_createtime(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  createtime_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fixbug.orderMessageResponse.createTime)
}
inline void orderMessageResponse::set_createtime(const void* value, size_t size) {
  
  createtime_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fixbug.orderMessageResponse.createTime)
}
inline std::string* orderMessageResponse::_internal_mutable_createtime() {
  
  return createtime_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* orderMessageResponse::release_createtime() {
  // @@protoc_insertion_point(field_release:fixbug.orderMessageResponse.createTime)
  
  return createtime_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void orderMessageResponse::set_allocated_createtime(std::string* createtime) {
  if (createtime != nullptr) {
    
  } else {
    
  }
  createtime_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), createtime);
  // @@protoc_insertion_point(field_set_allocated:fixbug.orderMessageResponse.createTime)
}

// int32 price = 2;
inline void orderMessageResponse::clear_price() {
  price_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 orderMessageResponse::_internal_price() const {
  return price_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 orderMessageResponse::price() const {
  // @@protoc_insertion_point(field_get:fixbug.orderMessageResponse.price)
  return _internal_price();
}
inline void orderMessageResponse::_internal_set_price(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  price_ = value;
}
inline void orderMessageResponse::set_price(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_price(value);
  // @@protoc_insertion_point(field_set:fixbug.orderMessageResponse.price)
}

// -------------------------------------------------------------------

// orderMessageRequest

// bytes orderNumber = 1;
inline void orderMessageRequest::clear_ordernumber() {
  ordernumber_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& orderMessageRequest::ordernumber() const {
  // @@protoc_insertion_point(field_get:fixbug.orderMessageRequest.orderNumber)
  return _internal_ordernumber();
}
inline void orderMessageRequest::set_ordernumber(const std::string& value) {
  _internal_set_ordernumber(value);
  // @@protoc_insertion_point(field_set:fixbug.orderMessageRequest.orderNumber)
}
inline std::string* orderMessageRequest::mutable_ordernumber() {
  // @@protoc_insertion_point(field_mutable:fixbug.orderMessageRequest.orderNumber)
  return _internal_mutable_ordernumber();
}
inline const std::string& orderMessageRequest::_internal_ordernumber() const {
  return ordernumber_.GetNoArena();
}
inline void orderMessageRequest::_internal_set_ordernumber(const std::string& value) {
  
  ordernumber_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void orderMessageRequest::set_ordernumber(std::string&& value) {
  
  ordernumber_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fixbug.orderMessageRequest.orderNumber)
}
inline void orderMessageRequest::set_ordernumber(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  ordernumber_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fixbug.orderMessageRequest.orderNumber)
}
inline void orderMessageRequest::set_ordernumber(const void* value, size_t size) {
  
  ordernumber_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fixbug.orderMessageRequest.orderNumber)
}
inline std::string* orderMessageRequest::_internal_mutable_ordernumber() {
  
  return ordernumber_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* orderMessageRequest::release_ordernumber() {
  // @@protoc_insertion_point(field_release:fixbug.orderMessageRequest.orderNumber)
  
  return ordernumber_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void orderMessageRequest::set_allocated_ordernumber(std::string* ordernumber) {
  if (ordernumber != nullptr) {
    
  } else {
    
  }
  ordernumber_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ordernumber);
  // @@protoc_insertion_point(field_set_allocated:fixbug.orderMessageRequest.orderNumber)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace fixbug

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_checkOrder_2eproto
